### ISSUE TITLE
Extract acceptance criteria from issues

### ISSUE THREAD

**Issue by GiuseppeBrunoSt** [Sergio-FreeJS/metricsJS#5]
Do you think there is a way where we would extract the acceptance criteria based off text such as "acceptance criteria:" or "acceptance criteria" ?

Acceptance criteria:
have another column in issue with the acceptance criteria

**Comment by Sergio-FreeJS** [comment]
Giuseppe
columns are dynamically added to the issues report if you use ** before and after a text
To add "**acceptance criteria**" column you must add ** before and after it.
S
